# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LookArt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LookArt
  pod 'GCDWebServer', '~> 3.0'
  pod 'SwifterSwift'
  pod 'SnapKit', '~> 5.0.0'
  pod 'RxSwift', '~> 6.1.0'
  pod 'RxCocoa', '~> 6.1.0'
  target 'LookArtTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LookArtUITests' do
    # Pods for testing
  end

end
