# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

post_install do |installer|
    # 获取Pods项目中的目标数组(targets）然后遍历目targets
    installer.pods_project.targets.each do |target|
        # 通过目标对象（target）获取构建配置数组 (build_configurations)遍历构建配置数组
        target.build_configurations.each do |config|
            # 修改构建配置对象中的构建设置 (build_settings），将iOS 部署目标版本设为 13.0
            config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = '13.0'
        end
    end
end

use_frameworks!

target 'LookArt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LookArt
  pod 'GCDWebServer', '~> 3.0'
  pod 'SwifterSwift'
  pod 'SnapKit', '~> 5.0.0'
  pod 'RxSwift', '6.1.0'
  pod 'RxCocoa', '6.1.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'ObjectMapper', '~> 3.5'
  pod 'PanModal'
  pod 'RealmSwift', '~>10'
  pod 'CryptoSwift', '~> 1.4.1'
  pod 'Kingfisher', '~> 6.3.1'
  pod 'Disk'
  pod 'Moya/RxSwift', '~> 15.0'
  pod 'ReachabilitySwift'
  pod 'SVProgressHUD'
  pod 'CollectionViewPagingLayout'
  pod 'CocoaDebug', :configurations => ['Debug']
  
  target 'LookArtTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  target 'LookArtUITests' do
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

end
